#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTJ.Person.DataLayer
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="PTJ")]
	public partial class DBPersonDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertAdress(Adress instance);
    partial void UpdateAdress(Adress instance);
    partial void DeleteAdress(Adress instance);
    partial void InsertAdressTyp(AdressTyp instance);
    partial void UpdateAdressTyp(AdressTyp instance);
    partial void DeleteAdressTyp(AdressTyp instance);
    partial void InsertAdressVariant(AdressVariant instance);
    partial void UpdateAdressVariant(AdressVariant instance);
    partial void DeleteAdressVariant(AdressVariant instance);
    partial void InsertGatuAdress(GatuAdress instance);
    partial void UpdateGatuAdress(GatuAdress instance);
    partial void DeleteGatuAdress(GatuAdress instance);
    partial void InsertMail(Mail instance);
    partial void UpdateMail(Mail instance);
    partial void DeleteMail(Mail instance);
    partial void InsertTelefon(Telefon instance);
    partial void UpdateTelefon(Telefon instance);
    partial void DeleteTelefon(Telefon instance);
    partial void InsertPerson(Person instance);
    partial void UpdatePerson(Person instance);
    partial void DeletePerson(Person instance);
    #endregion
		
		public DBPersonDataContext() : 
				base(global::PTJ.Person.DataLayer.Properties.Settings.Default.PTJConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DBPersonDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBPersonDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBPersonDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBPersonDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Adress> Adresses
		{
			get
			{
				return this.GetTable<Adress>();
			}
		}
		
		public System.Data.Linq.Table<AdressTyp> AdressTyps
		{
			get
			{
				return this.GetTable<AdressTyp>();
			}
		}
		
		public System.Data.Linq.Table<AdressVariant> AdressVariants
		{
			get
			{
				return this.GetTable<AdressVariant>();
			}
		}
		
		public System.Data.Linq.Table<GatuAdress> GatuAdresses
		{
			get
			{
				return this.GetTable<GatuAdress>();
			}
		}
		
		public System.Data.Linq.Table<Mail> Mails
		{
			get
			{
				return this.GetTable<Mail>();
			}
		}
		
		public System.Data.Linq.Table<Telefon> Telefons
		{
			get
			{
				return this.GetTable<Telefon>();
			}
		}
		
		public System.Data.Linq.Table<Person> Persons
		{
			get
			{
				return this.GetTable<Person>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="Adress.Adress")]
	public partial class Adress : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private int _AdressTyp_FKID;
		
		private System.Nullable<int> _Person_FKID;
		
		private System.Nullable<int> _Organisation_FKID;
		
		private int _AdressVariant_FKID;
		
		private System.DateTime _SkapadDatum;
		
		private System.Nullable<System.DateTime> _UpdateradDatum;
		
		private EntitySet<GatuAdress> _GatuAdresses;
		
		private EntitySet<Mail> _Mails;
		
		private EntitySet<Telefon> _Telefons;
		
		private EntityRef<AdressTyp> _AdressTyp;
		
		private EntityRef<AdressVariant> _AdressVariant;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnAdressTyp_FKIDChanging(int value);
    partial void OnAdressTyp_FKIDChanged();
    partial void OnPerson_FKIDChanging(System.Nullable<int> value);
    partial void OnPerson_FKIDChanged();
    partial void OnOrganisation_FKIDChanging(System.Nullable<int> value);
    partial void OnOrganisation_FKIDChanged();
    partial void OnAdressVariant_FKIDChanging(int value);
    partial void OnAdressVariant_FKIDChanged();
    partial void OnSkapadDatumChanging(System.DateTime value);
    partial void OnSkapadDatumChanged();
    partial void OnUpdateradDatumChanging(System.Nullable<System.DateTime> value);
    partial void OnUpdateradDatumChanged();
    #endregion
		
		public Adress()
		{
			this._GatuAdresses = new EntitySet<GatuAdress>(new Action<GatuAdress>(this.attach_GatuAdresses), new Action<GatuAdress>(this.detach_GatuAdresses));
			this._Mails = new EntitySet<Mail>(new Action<Mail>(this.attach_Mails), new Action<Mail>(this.detach_Mails));
			this._Telefons = new EntitySet<Telefon>(new Action<Telefon>(this.attach_Telefons), new Action<Telefon>(this.detach_Telefons));
			this._AdressTyp = default(EntityRef<AdressTyp>);
			this._AdressVariant = default(EntityRef<AdressVariant>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdressTyp_FKID", DbType="Int NOT NULL")]
		public int AdressTyp_FKID
		{
			get
			{
				return this._AdressTyp_FKID;
			}
			set
			{
				if ((this._AdressTyp_FKID != value))
				{
					if (this._AdressTyp.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnAdressTyp_FKIDChanging(value);
					this.SendPropertyChanging();
					this._AdressTyp_FKID = value;
					this.SendPropertyChanged("AdressTyp_FKID");
					this.OnAdressTyp_FKIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Person_FKID", DbType="Int")]
		public System.Nullable<int> Person_FKID
		{
			get
			{
				return this._Person_FKID;
			}
			set
			{
				if ((this._Person_FKID != value))
				{
					this.OnPerson_FKIDChanging(value);
					this.SendPropertyChanging();
					this._Person_FKID = value;
					this.SendPropertyChanged("Person_FKID");
					this.OnPerson_FKIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Organisation_FKID", DbType="Int")]
		public System.Nullable<int> Organisation_FKID
		{
			get
			{
				return this._Organisation_FKID;
			}
			set
			{
				if ((this._Organisation_FKID != value))
				{
					this.OnOrganisation_FKIDChanging(value);
					this.SendPropertyChanging();
					this._Organisation_FKID = value;
					this.SendPropertyChanged("Organisation_FKID");
					this.OnOrganisation_FKIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdressVariant_FKID", DbType="Int NOT NULL")]
		public int AdressVariant_FKID
		{
			get
			{
				return this._AdressVariant_FKID;
			}
			set
			{
				if ((this._AdressVariant_FKID != value))
				{
					if (this._AdressVariant.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnAdressVariant_FKIDChanging(value);
					this.SendPropertyChanging();
					this._AdressVariant_FKID = value;
					this.SendPropertyChanged("AdressVariant_FKID");
					this.OnAdressVariant_FKIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SkapadDatum", DbType="DateTime NOT NULL")]
		public System.DateTime SkapadDatum
		{
			get
			{
				return this._SkapadDatum;
			}
			set
			{
				if ((this._SkapadDatum != value))
				{
					this.OnSkapadDatumChanging(value);
					this.SendPropertyChanging();
					this._SkapadDatum = value;
					this.SendPropertyChanged("SkapadDatum");
					this.OnSkapadDatumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdateradDatum", DbType="DateTime")]
		public System.Nullable<System.DateTime> UpdateradDatum
		{
			get
			{
				return this._UpdateradDatum;
			}
			set
			{
				if ((this._UpdateradDatum != value))
				{
					this.OnUpdateradDatumChanging(value);
					this.SendPropertyChanging();
					this._UpdateradDatum = value;
					this.SendPropertyChanged("UpdateradDatum");
					this.OnUpdateradDatumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Adress_GatuAdress", Storage="_GatuAdresses", ThisKey="Id", OtherKey="AdressTyp_FKID")]
		public EntitySet<GatuAdress> GatuAdresses
		{
			get
			{
				return this._GatuAdresses;
			}
			set
			{
				this._GatuAdresses.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Adress_Mail", Storage="_Mails", ThisKey="Id", OtherKey="Adress_FKID")]
		public EntitySet<Mail> Mails
		{
			get
			{
				return this._Mails;
			}
			set
			{
				this._Mails.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Adress_Telefon", Storage="_Telefons", ThisKey="Id", OtherKey="Adress_FKID")]
		public EntitySet<Telefon> Telefons
		{
			get
			{
				return this._Telefons;
			}
			set
			{
				this._Telefons.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="AdressTyp_Adress", Storage="_AdressTyp", ThisKey="AdressTyp_FKID", OtherKey="Id", IsForeignKey=true)]
		public AdressTyp AdressTyp
		{
			get
			{
				return this._AdressTyp.Entity;
			}
			set
			{
				AdressTyp previousValue = this._AdressTyp.Entity;
				if (((previousValue != value) 
							|| (this._AdressTyp.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._AdressTyp.Entity = null;
						previousValue.Adresses.Remove(this);
					}
					this._AdressTyp.Entity = value;
					if ((value != null))
					{
						value.Adresses.Add(this);
						this._AdressTyp_FKID = value.Id;
					}
					else
					{
						this._AdressTyp_FKID = default(int);
					}
					this.SendPropertyChanged("AdressTyp");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="AdressVariant_Adress", Storage="_AdressVariant", ThisKey="AdressVariant_FKID", OtherKey="Id", IsForeignKey=true)]
		public AdressVariant AdressVariant
		{
			get
			{
				return this._AdressVariant.Entity;
			}
			set
			{
				AdressVariant previousValue = this._AdressVariant.Entity;
				if (((previousValue != value) 
							|| (this._AdressVariant.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._AdressVariant.Entity = null;
						previousValue.Adresses.Remove(this);
					}
					this._AdressVariant.Entity = value;
					if ((value != null))
					{
						value.Adresses.Add(this);
						this._AdressVariant_FKID = value.Id;
					}
					else
					{
						this._AdressVariant_FKID = default(int);
					}
					this.SendPropertyChanged("AdressVariant");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_GatuAdresses(GatuAdress entity)
		{
			this.SendPropertyChanging();
			entity.Adress = this;
		}
		
		private void detach_GatuAdresses(GatuAdress entity)
		{
			this.SendPropertyChanging();
			entity.Adress = null;
		}
		
		private void attach_Mails(Mail entity)
		{
			this.SendPropertyChanging();
			entity.Adress = this;
		}
		
		private void detach_Mails(Mail entity)
		{
			this.SendPropertyChanging();
			entity.Adress = null;
		}
		
		private void attach_Telefons(Telefon entity)
		{
			this.SendPropertyChanging();
			entity.Adress = this;
		}
		
		private void detach_Telefons(Telefon entity)
		{
			this.SendPropertyChanging();
			entity.Adress = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="Adress.AdressTyp")]
	public partial class AdressTyp : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Typ;
		
		private System.DateTime _SkapadDatum;
		
		private System.Nullable<System.DateTime> _UpdateradDatum;
		
		private EntitySet<Adress> _Adresses;
		
		private EntitySet<AdressVariant> _AdressVariants;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnTypChanging(string value);
    partial void OnTypChanged();
    partial void OnSkapadDatumChanging(System.DateTime value);
    partial void OnSkapadDatumChanged();
    partial void OnUpdateradDatumChanging(System.Nullable<System.DateTime> value);
    partial void OnUpdateradDatumChanged();
    #endregion
		
		public AdressTyp()
		{
			this._Adresses = new EntitySet<Adress>(new Action<Adress>(this.attach_Adresses), new Action<Adress>(this.detach_Adresses));
			this._AdressVariants = new EntitySet<AdressVariant>(new Action<AdressVariant>(this.attach_AdressVariants), new Action<AdressVariant>(this.detach_AdressVariants));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Typ", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Typ
		{
			get
			{
				return this._Typ;
			}
			set
			{
				if ((this._Typ != value))
				{
					this.OnTypChanging(value);
					this.SendPropertyChanging();
					this._Typ = value;
					this.SendPropertyChanged("Typ");
					this.OnTypChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SkapadDatum", DbType="DateTime NOT NULL")]
		public System.DateTime SkapadDatum
		{
			get
			{
				return this._SkapadDatum;
			}
			set
			{
				if ((this._SkapadDatum != value))
				{
					this.OnSkapadDatumChanging(value);
					this.SendPropertyChanging();
					this._SkapadDatum = value;
					this.SendPropertyChanged("SkapadDatum");
					this.OnSkapadDatumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdateradDatum", DbType="DateTime")]
		public System.Nullable<System.DateTime> UpdateradDatum
		{
			get
			{
				return this._UpdateradDatum;
			}
			set
			{
				if ((this._UpdateradDatum != value))
				{
					this.OnUpdateradDatumChanging(value);
					this.SendPropertyChanging();
					this._UpdateradDatum = value;
					this.SendPropertyChanged("UpdateradDatum");
					this.OnUpdateradDatumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="AdressTyp_Adress", Storage="_Adresses", ThisKey="Id", OtherKey="AdressTyp_FKID")]
		public EntitySet<Adress> Adresses
		{
			get
			{
				return this._Adresses;
			}
			set
			{
				this._Adresses.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="AdressTyp_AdressVariant", Storage="_AdressVariants", ThisKey="Id", OtherKey="AdressTyp_FKID")]
		public EntitySet<AdressVariant> AdressVariants
		{
			get
			{
				return this._AdressVariants;
			}
			set
			{
				this._AdressVariants.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Adresses(Adress entity)
		{
			this.SendPropertyChanging();
			entity.AdressTyp = this;
		}
		
		private void detach_Adresses(Adress entity)
		{
			this.SendPropertyChanging();
			entity.AdressTyp = null;
		}
		
		private void attach_AdressVariants(AdressVariant entity)
		{
			this.SendPropertyChanging();
			entity.AdressTyp = this;
		}
		
		private void detach_AdressVariants(AdressVariant entity)
		{
			this.SendPropertyChanging();
			entity.AdressTyp = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="Adress.AdressVariant")]
	public partial class AdressVariant : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private int _AdressTyp_FKID;
		
		private string _Variant;
		
		private System.DateTime _SkapadDatum;
		
		private System.Nullable<System.DateTime> _UpdateradDatum;
		
		private EntitySet<Adress> _Adresses;
		
		private EntityRef<AdressTyp> _AdressTyp;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnAdressTyp_FKIDChanging(int value);
    partial void OnAdressTyp_FKIDChanged();
    partial void OnVariantChanging(string value);
    partial void OnVariantChanged();
    partial void OnSkapadDatumChanging(System.DateTime value);
    partial void OnSkapadDatumChanged();
    partial void OnUpdateradDatumChanging(System.Nullable<System.DateTime> value);
    partial void OnUpdateradDatumChanged();
    #endregion
		
		public AdressVariant()
		{
			this._Adresses = new EntitySet<Adress>(new Action<Adress>(this.attach_Adresses), new Action<Adress>(this.detach_Adresses));
			this._AdressTyp = default(EntityRef<AdressTyp>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdressTyp_FKID", DbType="Int NOT NULL")]
		public int AdressTyp_FKID
		{
			get
			{
				return this._AdressTyp_FKID;
			}
			set
			{
				if ((this._AdressTyp_FKID != value))
				{
					if (this._AdressTyp.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnAdressTyp_FKIDChanging(value);
					this.SendPropertyChanging();
					this._AdressTyp_FKID = value;
					this.SendPropertyChanged("AdressTyp_FKID");
					this.OnAdressTyp_FKIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Variant", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string Variant
		{
			get
			{
				return this._Variant;
			}
			set
			{
				if ((this._Variant != value))
				{
					this.OnVariantChanging(value);
					this.SendPropertyChanging();
					this._Variant = value;
					this.SendPropertyChanged("Variant");
					this.OnVariantChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SkapadDatum", DbType="DateTime NOT NULL")]
		public System.DateTime SkapadDatum
		{
			get
			{
				return this._SkapadDatum;
			}
			set
			{
				if ((this._SkapadDatum != value))
				{
					this.OnSkapadDatumChanging(value);
					this.SendPropertyChanging();
					this._SkapadDatum = value;
					this.SendPropertyChanged("SkapadDatum");
					this.OnSkapadDatumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdateradDatum", DbType="DateTime")]
		public System.Nullable<System.DateTime> UpdateradDatum
		{
			get
			{
				return this._UpdateradDatum;
			}
			set
			{
				if ((this._UpdateradDatum != value))
				{
					this.OnUpdateradDatumChanging(value);
					this.SendPropertyChanging();
					this._UpdateradDatum = value;
					this.SendPropertyChanged("UpdateradDatum");
					this.OnUpdateradDatumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="AdressVariant_Adress", Storage="_Adresses", ThisKey="Id", OtherKey="AdressVariant_FKID")]
		public EntitySet<Adress> Adresses
		{
			get
			{
				return this._Adresses;
			}
			set
			{
				this._Adresses.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="AdressTyp_AdressVariant", Storage="_AdressTyp", ThisKey="AdressTyp_FKID", OtherKey="Id", IsForeignKey=true)]
		public AdressTyp AdressTyp
		{
			get
			{
				return this._AdressTyp.Entity;
			}
			set
			{
				AdressTyp previousValue = this._AdressTyp.Entity;
				if (((previousValue != value) 
							|| (this._AdressTyp.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._AdressTyp.Entity = null;
						previousValue.AdressVariants.Remove(this);
					}
					this._AdressTyp.Entity = value;
					if ((value != null))
					{
						value.AdressVariants.Add(this);
						this._AdressTyp_FKID = value.Id;
					}
					else
					{
						this._AdressTyp_FKID = default(int);
					}
					this.SendPropertyChanged("AdressTyp");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Adresses(Adress entity)
		{
			this.SendPropertyChanging();
			entity.AdressVariant = this;
		}
		
		private void detach_Adresses(Adress entity)
		{
			this.SendPropertyChanging();
			entity.AdressVariant = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="Adress.GatuAdress")]
	public partial class GatuAdress : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private int _Adress_FKID;
		
		private System.Nullable<int> _AdressTyp_FKID;
		
		private System.Nullable<int> _AdressVariant_FKID;
		
		private string _AdressRad1;
		
		private string _AdressRad2;
		
		private string _AdressRad3;
		
		private string _AdressRad4;
		
		private string _AdressRad5;
		
		private decimal _Postnummer;
		
		private string _Stad;
		
		private string _Land;
		
		private System.DateTime _SkapadDatum;
		
		private System.Nullable<System.DateTime> _UpdateradDatum;
		
		private EntityRef<Adress> _Adress;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnAdress_FKIDChanging(int value);
    partial void OnAdress_FKIDChanged();
    partial void OnAdressTyp_FKIDChanging(System.Nullable<int> value);
    partial void OnAdressTyp_FKIDChanged();
    partial void OnAdressVariant_FKIDChanging(System.Nullable<int> value);
    partial void OnAdressVariant_FKIDChanged();
    partial void OnAdressRad1Changing(string value);
    partial void OnAdressRad1Changed();
    partial void OnAdressRad2Changing(string value);
    partial void OnAdressRad2Changed();
    partial void OnAdressRad3Changing(string value);
    partial void OnAdressRad3Changed();
    partial void OnAdressRad4Changing(string value);
    partial void OnAdressRad4Changed();
    partial void OnAdressRad5Changing(string value);
    partial void OnAdressRad5Changed();
    partial void OnPostnummerChanging(decimal value);
    partial void OnPostnummerChanged();
    partial void OnStadChanging(string value);
    partial void OnStadChanged();
    partial void OnLandChanging(string value);
    partial void OnLandChanged();
    partial void OnSkapadDatumChanging(System.DateTime value);
    partial void OnSkapadDatumChanged();
    partial void OnUpdateradDatumChanging(System.Nullable<System.DateTime> value);
    partial void OnUpdateradDatumChanged();
    #endregion
		
		public GatuAdress()
		{
			this._Adress = default(EntityRef<Adress>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Adress_FKID", DbType="Int NOT NULL")]
		public int Adress_FKID
		{
			get
			{
				return this._Adress_FKID;
			}
			set
			{
				if ((this._Adress_FKID != value))
				{
					this.OnAdress_FKIDChanging(value);
					this.SendPropertyChanging();
					this._Adress_FKID = value;
					this.SendPropertyChanged("Adress_FKID");
					this.OnAdress_FKIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdressTyp_FKID", DbType="Int")]
		public System.Nullable<int> AdressTyp_FKID
		{
			get
			{
				return this._AdressTyp_FKID;
			}
			set
			{
				if ((this._AdressTyp_FKID != value))
				{
					if (this._Adress.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnAdressTyp_FKIDChanging(value);
					this.SendPropertyChanging();
					this._AdressTyp_FKID = value;
					this.SendPropertyChanged("AdressTyp_FKID");
					this.OnAdressTyp_FKIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdressVariant_FKID", DbType="Int")]
		public System.Nullable<int> AdressVariant_FKID
		{
			get
			{
				return this._AdressVariant_FKID;
			}
			set
			{
				if ((this._AdressVariant_FKID != value))
				{
					this.OnAdressVariant_FKIDChanging(value);
					this.SendPropertyChanging();
					this._AdressVariant_FKID = value;
					this.SendPropertyChanged("AdressVariant_FKID");
					this.OnAdressVariant_FKIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdressRad1", DbType="NVarChar(255)")]
		public string AdressRad1
		{
			get
			{
				return this._AdressRad1;
			}
			set
			{
				if ((this._AdressRad1 != value))
				{
					this.OnAdressRad1Changing(value);
					this.SendPropertyChanging();
					this._AdressRad1 = value;
					this.SendPropertyChanged("AdressRad1");
					this.OnAdressRad1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdressRad2", DbType="NVarChar(255)")]
		public string AdressRad2
		{
			get
			{
				return this._AdressRad2;
			}
			set
			{
				if ((this._AdressRad2 != value))
				{
					this.OnAdressRad2Changing(value);
					this.SendPropertyChanging();
					this._AdressRad2 = value;
					this.SendPropertyChanged("AdressRad2");
					this.OnAdressRad2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdressRad3", DbType="NVarChar(255)")]
		public string AdressRad3
		{
			get
			{
				return this._AdressRad3;
			}
			set
			{
				if ((this._AdressRad3 != value))
				{
					this.OnAdressRad3Changing(value);
					this.SendPropertyChanging();
					this._AdressRad3 = value;
					this.SendPropertyChanged("AdressRad3");
					this.OnAdressRad3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdressRad4", DbType="NVarChar(255)")]
		public string AdressRad4
		{
			get
			{
				return this._AdressRad4;
			}
			set
			{
				if ((this._AdressRad4 != value))
				{
					this.OnAdressRad4Changing(value);
					this.SendPropertyChanging();
					this._AdressRad4 = value;
					this.SendPropertyChanged("AdressRad4");
					this.OnAdressRad4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdressRad5", DbType="NVarChar(255)")]
		public string AdressRad5
		{
			get
			{
				return this._AdressRad5;
			}
			set
			{
				if ((this._AdressRad5 != value))
				{
					this.OnAdressRad5Changing(value);
					this.SendPropertyChanging();
					this._AdressRad5 = value;
					this.SendPropertyChanged("AdressRad5");
					this.OnAdressRad5Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Postnummer", DbType="Decimal(18,0) NOT NULL")]
		public decimal Postnummer
		{
			get
			{
				return this._Postnummer;
			}
			set
			{
				if ((this._Postnummer != value))
				{
					this.OnPostnummerChanging(value);
					this.SendPropertyChanging();
					this._Postnummer = value;
					this.SendPropertyChanged("Postnummer");
					this.OnPostnummerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Stad", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string Stad
		{
			get
			{
				return this._Stad;
			}
			set
			{
				if ((this._Stad != value))
				{
					this.OnStadChanging(value);
					this.SendPropertyChanging();
					this._Stad = value;
					this.SendPropertyChanged("Stad");
					this.OnStadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Land", DbType="NVarChar(255)")]
		public string Land
		{
			get
			{
				return this._Land;
			}
			set
			{
				if ((this._Land != value))
				{
					this.OnLandChanging(value);
					this.SendPropertyChanging();
					this._Land = value;
					this.SendPropertyChanged("Land");
					this.OnLandChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SkapadDatum", DbType="DateTime NOT NULL")]
		public System.DateTime SkapadDatum
		{
			get
			{
				return this._SkapadDatum;
			}
			set
			{
				if ((this._SkapadDatum != value))
				{
					this.OnSkapadDatumChanging(value);
					this.SendPropertyChanging();
					this._SkapadDatum = value;
					this.SendPropertyChanged("SkapadDatum");
					this.OnSkapadDatumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdateradDatum", DbType="DateTime")]
		public System.Nullable<System.DateTime> UpdateradDatum
		{
			get
			{
				return this._UpdateradDatum;
			}
			set
			{
				if ((this._UpdateradDatum != value))
				{
					this.OnUpdateradDatumChanging(value);
					this.SendPropertyChanging();
					this._UpdateradDatum = value;
					this.SendPropertyChanged("UpdateradDatum");
					this.OnUpdateradDatumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Adress_GatuAdress", Storage="_Adress", ThisKey="AdressTyp_FKID", OtherKey="Id", IsForeignKey=true)]
		public Adress Adress
		{
			get
			{
				return this._Adress.Entity;
			}
			set
			{
				Adress previousValue = this._Adress.Entity;
				if (((previousValue != value) 
							|| (this._Adress.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Adress.Entity = null;
						previousValue.GatuAdresses.Remove(this);
					}
					this._Adress.Entity = value;
					if ((value != null))
					{
						value.GatuAdresses.Add(this);
						this._AdressTyp_FKID = value.Id;
					}
					else
					{
						this._AdressTyp_FKID = default(Nullable<int>);
					}
					this.SendPropertyChanged("Adress");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="Adress.Mail")]
	public partial class Mail : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private int _Adress_FKID;
		
		private System.Nullable<int> _AdressTyp_FKID;
		
		private System.Nullable<int> _AdressVariant_FKID;
		
		private string _MailAdress;
		
		private System.DateTime _SkapadDatum;
		
		private System.Nullable<System.DateTime> _UpdateradDatum;
		
		private EntityRef<Adress> _Adress;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnAdress_FKIDChanging(int value);
    partial void OnAdress_FKIDChanged();
    partial void OnAdressTyp_FKIDChanging(System.Nullable<int> value);
    partial void OnAdressTyp_FKIDChanged();
    partial void OnAdressVariant_FKIDChanging(System.Nullable<int> value);
    partial void OnAdressVariant_FKIDChanged();
    partial void OnMailAdressChanging(string value);
    partial void OnMailAdressChanged();
    partial void OnSkapadDatumChanging(System.DateTime value);
    partial void OnSkapadDatumChanged();
    partial void OnUpdateradDatumChanging(System.Nullable<System.DateTime> value);
    partial void OnUpdateradDatumChanged();
    #endregion
		
		public Mail()
		{
			this._Adress = default(EntityRef<Adress>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Adress_FKID", DbType="Int NOT NULL")]
		public int Adress_FKID
		{
			get
			{
				return this._Adress_FKID;
			}
			set
			{
				if ((this._Adress_FKID != value))
				{
					if (this._Adress.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnAdress_FKIDChanging(value);
					this.SendPropertyChanging();
					this._Adress_FKID = value;
					this.SendPropertyChanged("Adress_FKID");
					this.OnAdress_FKIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdressTyp_FKID", DbType="Int")]
		public System.Nullable<int> AdressTyp_FKID
		{
			get
			{
				return this._AdressTyp_FKID;
			}
			set
			{
				if ((this._AdressTyp_FKID != value))
				{
					this.OnAdressTyp_FKIDChanging(value);
					this.SendPropertyChanging();
					this._AdressTyp_FKID = value;
					this.SendPropertyChanged("AdressTyp_FKID");
					this.OnAdressTyp_FKIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdressVariant_FKID", DbType="Int")]
		public System.Nullable<int> AdressVariant_FKID
		{
			get
			{
				return this._AdressVariant_FKID;
			}
			set
			{
				if ((this._AdressVariant_FKID != value))
				{
					this.OnAdressVariant_FKIDChanging(value);
					this.SendPropertyChanging();
					this._AdressVariant_FKID = value;
					this.SendPropertyChanged("AdressVariant_FKID");
					this.OnAdressVariant_FKIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MailAdress", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string MailAdress
		{
			get
			{
				return this._MailAdress;
			}
			set
			{
				if ((this._MailAdress != value))
				{
					this.OnMailAdressChanging(value);
					this.SendPropertyChanging();
					this._MailAdress = value;
					this.SendPropertyChanged("MailAdress");
					this.OnMailAdressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SkapadDatum", DbType="DateTime NOT NULL")]
		public System.DateTime SkapadDatum
		{
			get
			{
				return this._SkapadDatum;
			}
			set
			{
				if ((this._SkapadDatum != value))
				{
					this.OnSkapadDatumChanging(value);
					this.SendPropertyChanging();
					this._SkapadDatum = value;
					this.SendPropertyChanged("SkapadDatum");
					this.OnSkapadDatumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdateradDatum", DbType="DateTime")]
		public System.Nullable<System.DateTime> UpdateradDatum
		{
			get
			{
				return this._UpdateradDatum;
			}
			set
			{
				if ((this._UpdateradDatum != value))
				{
					this.OnUpdateradDatumChanging(value);
					this.SendPropertyChanging();
					this._UpdateradDatum = value;
					this.SendPropertyChanged("UpdateradDatum");
					this.OnUpdateradDatumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Adress_Mail", Storage="_Adress", ThisKey="Adress_FKID", OtherKey="Id", IsForeignKey=true)]
		public Adress Adress
		{
			get
			{
				return this._Adress.Entity;
			}
			set
			{
				Adress previousValue = this._Adress.Entity;
				if (((previousValue != value) 
							|| (this._Adress.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Adress.Entity = null;
						previousValue.Mails.Remove(this);
					}
					this._Adress.Entity = value;
					if ((value != null))
					{
						value.Mails.Add(this);
						this._Adress_FKID = value.Id;
					}
					else
					{
						this._Adress_FKID = default(int);
					}
					this.SendPropertyChanged("Adress");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="Adress.Telefon")]
	public partial class Telefon : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private int _Adress_FKID;
		
		private System.Nullable<int> _AdressTyp_FKID;
		
		private System.Nullable<int> _AdressVariant_FKID;
		
		private decimal _TelefonNummer;
		
		private System.DateTime _SkapadDatum;
		
		private System.Nullable<System.DateTime> _UpdateradDatum;
		
		private EntityRef<Adress> _Adress;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnAdress_FKIDChanging(int value);
    partial void OnAdress_FKIDChanged();
    partial void OnAdressTyp_FKIDChanging(System.Nullable<int> value);
    partial void OnAdressTyp_FKIDChanged();
    partial void OnAdressVariant_FKIDChanging(System.Nullable<int> value);
    partial void OnAdressVariant_FKIDChanged();
    partial void OnTelefonNummerChanging(decimal value);
    partial void OnTelefonNummerChanged();
    partial void OnSkapadDatumChanging(System.DateTime value);
    partial void OnSkapadDatumChanged();
    partial void OnUpdateradDatumChanging(System.Nullable<System.DateTime> value);
    partial void OnUpdateradDatumChanged();
    #endregion
		
		public Telefon()
		{
			this._Adress = default(EntityRef<Adress>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Adress_FKID", DbType="Int NOT NULL")]
		public int Adress_FKID
		{
			get
			{
				return this._Adress_FKID;
			}
			set
			{
				if ((this._Adress_FKID != value))
				{
					if (this._Adress.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnAdress_FKIDChanging(value);
					this.SendPropertyChanging();
					this._Adress_FKID = value;
					this.SendPropertyChanged("Adress_FKID");
					this.OnAdress_FKIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdressTyp_FKID", DbType="Int")]
		public System.Nullable<int> AdressTyp_FKID
		{
			get
			{
				return this._AdressTyp_FKID;
			}
			set
			{
				if ((this._AdressTyp_FKID != value))
				{
					this.OnAdressTyp_FKIDChanging(value);
					this.SendPropertyChanging();
					this._AdressTyp_FKID = value;
					this.SendPropertyChanged("AdressTyp_FKID");
					this.OnAdressTyp_FKIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdressVariant_FKID", DbType="Int")]
		public System.Nullable<int> AdressVariant_FKID
		{
			get
			{
				return this._AdressVariant_FKID;
			}
			set
			{
				if ((this._AdressVariant_FKID != value))
				{
					this.OnAdressVariant_FKIDChanging(value);
					this.SendPropertyChanging();
					this._AdressVariant_FKID = value;
					this.SendPropertyChanged("AdressVariant_FKID");
					this.OnAdressVariant_FKIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TelefonNummer", DbType="Decimal(25,0) NOT NULL")]
		public decimal TelefonNummer
		{
			get
			{
				return this._TelefonNummer;
			}
			set
			{
				if ((this._TelefonNummer != value))
				{
					this.OnTelefonNummerChanging(value);
					this.SendPropertyChanging();
					this._TelefonNummer = value;
					this.SendPropertyChanged("TelefonNummer");
					this.OnTelefonNummerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SkapadDatum", DbType="DateTime NOT NULL")]
		public System.DateTime SkapadDatum
		{
			get
			{
				return this._SkapadDatum;
			}
			set
			{
				if ((this._SkapadDatum != value))
				{
					this.OnSkapadDatumChanging(value);
					this.SendPropertyChanging();
					this._SkapadDatum = value;
					this.SendPropertyChanged("SkapadDatum");
					this.OnSkapadDatumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdateradDatum", DbType="DateTime")]
		public System.Nullable<System.DateTime> UpdateradDatum
		{
			get
			{
				return this._UpdateradDatum;
			}
			set
			{
				if ((this._UpdateradDatum != value))
				{
					this.OnUpdateradDatumChanging(value);
					this.SendPropertyChanging();
					this._UpdateradDatum = value;
					this.SendPropertyChanged("UpdateradDatum");
					this.OnUpdateradDatumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Adress_Telefon", Storage="_Adress", ThisKey="Adress_FKID", OtherKey="Id", IsForeignKey=true)]
		public Adress Adress
		{
			get
			{
				return this._Adress.Entity;
			}
			set
			{
				Adress previousValue = this._Adress.Entity;
				if (((previousValue != value) 
							|| (this._Adress.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Adress.Entity = null;
						previousValue.Telefons.Remove(this);
					}
					this._Adress.Entity = value;
					if ((value != null))
					{
						value.Telefons.Add(this);
						this._Adress_FKID = value.Id;
					}
					else
					{
						this._Adress_FKID = default(int);
					}
					this.SendPropertyChanged("Adress");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="Person.Person")]
	public partial class Person : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _FörNamn;
		
		private string _MellanNamn;
		
		private string _Efternamn;
		
		private string _PersonNummer;
		
		private System.DateTime _SkapadDatum;
		
		private System.Nullable<System.DateTime> _UpdateradDatum;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnFörNamnChanging(string value);
    partial void OnFörNamnChanged();
    partial void OnMellanNamnChanging(string value);
    partial void OnMellanNamnChanged();
    partial void OnEfternamnChanging(string value);
    partial void OnEfternamnChanged();
    partial void OnPersonNummerChanging(string value);
    partial void OnPersonNummerChanged();
    partial void OnSkapadDatumChanging(System.DateTime value);
    partial void OnSkapadDatumChanged();
    partial void OnUpdateradDatumChanging(System.Nullable<System.DateTime> value);
    partial void OnUpdateradDatumChanged();
    #endregion
		
		public Person()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FörNamn", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string FörNamn
		{
			get
			{
				return this._FörNamn;
			}
			set
			{
				if ((this._FörNamn != value))
				{
					this.OnFörNamnChanging(value);
					this.SendPropertyChanging();
					this._FörNamn = value;
					this.SendPropertyChanged("FörNamn");
					this.OnFörNamnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MellanNamn", DbType="NVarChar(255)")]
		public string MellanNamn
		{
			get
			{
				return this._MellanNamn;
			}
			set
			{
				if ((this._MellanNamn != value))
				{
					this.OnMellanNamnChanging(value);
					this.SendPropertyChanging();
					this._MellanNamn = value;
					this.SendPropertyChanged("MellanNamn");
					this.OnMellanNamnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Efternamn", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string Efternamn
		{
			get
			{
				return this._Efternamn;
			}
			set
			{
				if ((this._Efternamn != value))
				{
					this.OnEfternamnChanging(value);
					this.SendPropertyChanging();
					this._Efternamn = value;
					this.SendPropertyChanged("Efternamn");
					this.OnEfternamnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PersonNummer", DbType="VarChar(12) NOT NULL", CanBeNull=false)]
		public string PersonNummer
		{
			get
			{
				return this._PersonNummer;
			}
			set
			{
				if ((this._PersonNummer != value))
				{
					this.OnPersonNummerChanging(value);
					this.SendPropertyChanging();
					this._PersonNummer = value;
					this.SendPropertyChanged("PersonNummer");
					this.OnPersonNummerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SkapadDatum", DbType="DateTime NOT NULL")]
		public System.DateTime SkapadDatum
		{
			get
			{
				return this._SkapadDatum;
			}
			set
			{
				if ((this._SkapadDatum != value))
				{
					this.OnSkapadDatumChanging(value);
					this.SendPropertyChanging();
					this._SkapadDatum = value;
					this.SendPropertyChanged("SkapadDatum");
					this.OnSkapadDatumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdateradDatum", DbType="DateTime")]
		public System.Nullable<System.DateTime> UpdateradDatum
		{
			get
			{
				return this._UpdateradDatum;
			}
			set
			{
				if ((this._UpdateradDatum != value))
				{
					this.OnUpdateradDatumChanging(value);
					this.SendPropertyChanging();
					this._UpdateradDatum = value;
					this.SendPropertyChanged("UpdateradDatum");
					this.OnUpdateradDatumChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
