//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace PTJ.Person.Presentation.TelefonService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="TelefonServiceSoap", Namespace="http://tempuri.org/")]
    public partial class TelefonService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private PTJSoapHeader pTJSoapHeaderValueField;
        
        private System.Threading.SendOrPostCallback GetAllOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetByIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetByAdressOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetByTelefonNumberOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddTelefonOperationCompleted;
        
        private System.Threading.SendOrPostCallback ChangeTelefonOperationCompleted;
        
        private System.Threading.SendOrPostCallback RemoveTelefonOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCurrentTimeViewOperationCompleted;
        
        private System.Threading.SendOrPostCallback SetCurrentTimeViewOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public TelefonService() {
            this.Url = global::PTJ.Person.Presentation.Properties.Settings.Default.PTJ_Person_Presentation_TelefonService_TelefonService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public PTJSoapHeader PTJSoapHeaderValue {
            get {
                return this.pTJSoapHeaderValueField;
            }
            set {
                this.pTJSoapHeaderValueField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetAllCompletedEventHandler GetAllCompleted;
        
        /// <remarks/>
        public event GetByIdCompletedEventHandler GetByIdCompleted;
        
        /// <remarks/>
        public event GetByAdressCompletedEventHandler GetByAdressCompleted;
        
        /// <remarks/>
        public event GetByTelefonNumberCompletedEventHandler GetByTelefonNumberCompleted;
        
        /// <remarks/>
        public event AddTelefonCompletedEventHandler AddTelefonCompleted;
        
        /// <remarks/>
        public event ChangeTelefonCompletedEventHandler ChangeTelefonCompleted;
        
        /// <remarks/>
        public event RemoveTelefonCompletedEventHandler RemoveTelefonCompleted;
        
        /// <remarks/>
        public event GetCurrentTimeViewCompletedEventHandler GetCurrentTimeViewCompleted;
        
        /// <remarks/>
        public event SetCurrentTimeViewCompletedEventHandler SetCurrentTimeViewCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("PTJSoapHeaderValue", Direction=System.Web.Services.Protocols.SoapHeaderDirection.InOut)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAll", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TransportMessageOfArrayOfTelefonSchema GetAll() {
            object[] results = this.Invoke("GetAll", new object[0]);
            return ((TransportMessageOfArrayOfTelefonSchema)(results[0]));
        }
        
        /// <remarks/>
        public void GetAllAsync() {
            this.GetAllAsync(null);
        }
        
        /// <remarks/>
        public void GetAllAsync(object userState) {
            if ((this.GetAllOperationCompleted == null)) {
                this.GetAllOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllOperationCompleted);
            }
            this.InvokeAsync("GetAll", new object[0], this.GetAllOperationCompleted, userState);
        }
        
        private void OnGetAllOperationCompleted(object arg) {
            if ((this.GetAllCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllCompleted(this, new GetAllCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("PTJSoapHeaderValue", Direction=System.Web.Services.Protocols.SoapHeaderDirection.InOut)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ById", RequestElementName="ById", RequestNamespace="http://tempuri.org/", ResponseElementName="ByIdResponse", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("ByIdResult")]
        public TransportMessageOfTelefonSchema GetById(int id) {
            object[] results = this.Invoke("GetById", new object[] {
                        id});
            return ((TransportMessageOfTelefonSchema)(results[0]));
        }
        
        /// <remarks/>
        public void GetByIdAsync(int id) {
            this.GetByIdAsync(id, null);
        }
        
        /// <remarks/>
        public void GetByIdAsync(int id, object userState) {
            if ((this.GetByIdOperationCompleted == null)) {
                this.GetByIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetByIdOperationCompleted);
            }
            this.InvokeAsync("GetById", new object[] {
                        id}, this.GetByIdOperationCompleted, userState);
        }
        
        private void OnGetByIdOperationCompleted(object arg) {
            if ((this.GetByIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetByIdCompleted(this, new GetByIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("PTJSoapHeaderValue", Direction=System.Web.Services.Protocols.SoapHeaderDirection.InOut)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetByAdress", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TransportMessageOfArrayOfKeyValueOfTelefonSchemaAdressSchema GetByAdress(int id) {
            object[] results = this.Invoke("GetByAdress", new object[] {
                        id});
            return ((TransportMessageOfArrayOfKeyValueOfTelefonSchemaAdressSchema)(results[0]));
        }
        
        /// <remarks/>
        public void GetByAdressAsync(int id) {
            this.GetByAdressAsync(id, null);
        }
        
        /// <remarks/>
        public void GetByAdressAsync(int id, object userState) {
            if ((this.GetByAdressOperationCompleted == null)) {
                this.GetByAdressOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetByAdressOperationCompleted);
            }
            this.InvokeAsync("GetByAdress", new object[] {
                        id}, this.GetByAdressOperationCompleted, userState);
        }
        
        private void OnGetByAdressOperationCompleted(object arg) {
            if ((this.GetByAdressCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetByAdressCompleted(this, new GetByAdressCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("PTJSoapHeaderValue", Direction=System.Web.Services.Protocols.SoapHeaderDirection.InOut)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetByTelefonNumber", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TransportMessageOfArrayOfTelefonSchema GetByTelefonNumber(string name) {
            object[] results = this.Invoke("GetByTelefonNumber", new object[] {
                        name});
            return ((TransportMessageOfArrayOfTelefonSchema)(results[0]));
        }
        
        /// <remarks/>
        public void GetByTelefonNumberAsync(string name) {
            this.GetByTelefonNumberAsync(name, null);
        }
        
        /// <remarks/>
        public void GetByTelefonNumberAsync(string name, object userState) {
            if ((this.GetByTelefonNumberOperationCompleted == null)) {
                this.GetByTelefonNumberOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetByTelefonNumberOperationCompleted);
            }
            this.InvokeAsync("GetByTelefonNumber", new object[] {
                        name}, this.GetByTelefonNumberOperationCompleted, userState);
        }
        
        private void OnGetByTelefonNumberOperationCompleted(object arg) {
            if ((this.GetByTelefonNumberCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetByTelefonNumberCompleted(this, new GetByTelefonNumberCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("PTJSoapHeaderValue", Direction=System.Web.Services.Protocols.SoapHeaderDirection.InOut)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AddTelefon", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TransportMessageOfArrayOfTelefonSchema AddTelefon(TelefonSchema[] lstItems) {
            object[] results = this.Invoke("AddTelefon", new object[] {
                        lstItems});
            return ((TransportMessageOfArrayOfTelefonSchema)(results[0]));
        }
        
        /// <remarks/>
        public void AddTelefonAsync(TelefonSchema[] lstItems) {
            this.AddTelefonAsync(lstItems, null);
        }
        
        /// <remarks/>
        public void AddTelefonAsync(TelefonSchema[] lstItems, object userState) {
            if ((this.AddTelefonOperationCompleted == null)) {
                this.AddTelefonOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddTelefonOperationCompleted);
            }
            this.InvokeAsync("AddTelefon", new object[] {
                        lstItems}, this.AddTelefonOperationCompleted, userState);
        }
        
        private void OnAddTelefonOperationCompleted(object arg) {
            if ((this.AddTelefonCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddTelefonCompleted(this, new AddTelefonCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("PTJSoapHeaderValue", Direction=System.Web.Services.Protocols.SoapHeaderDirection.InOut)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ChangeTelefon", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TransportMessageOfArrayOfTelefonSchema ChangeTelefon(TelefonSchema[] lstItems) {
            object[] results = this.Invoke("ChangeTelefon", new object[] {
                        lstItems});
            return ((TransportMessageOfArrayOfTelefonSchema)(results[0]));
        }
        
        /// <remarks/>
        public void ChangeTelefonAsync(TelefonSchema[] lstItems) {
            this.ChangeTelefonAsync(lstItems, null);
        }
        
        /// <remarks/>
        public void ChangeTelefonAsync(TelefonSchema[] lstItems, object userState) {
            if ((this.ChangeTelefonOperationCompleted == null)) {
                this.ChangeTelefonOperationCompleted = new System.Threading.SendOrPostCallback(this.OnChangeTelefonOperationCompleted);
            }
            this.InvokeAsync("ChangeTelefon", new object[] {
                        lstItems}, this.ChangeTelefonOperationCompleted, userState);
        }
        
        private void OnChangeTelefonOperationCompleted(object arg) {
            if ((this.ChangeTelefonCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ChangeTelefonCompleted(this, new ChangeTelefonCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("PTJSoapHeaderValue", Direction=System.Web.Services.Protocols.SoapHeaderDirection.InOut)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RemoveTelefon", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TransportMessageOfArrayOfTelefonSchema RemoveTelefon(TelefonSchema[] lstItems) {
            object[] results = this.Invoke("RemoveTelefon", new object[] {
                        lstItems});
            return ((TransportMessageOfArrayOfTelefonSchema)(results[0]));
        }
        
        /// <remarks/>
        public void RemoveTelefonAsync(TelefonSchema[] lstItems) {
            this.RemoveTelefonAsync(lstItems, null);
        }
        
        /// <remarks/>
        public void RemoveTelefonAsync(TelefonSchema[] lstItems, object userState) {
            if ((this.RemoveTelefonOperationCompleted == null)) {
                this.RemoveTelefonOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRemoveTelefonOperationCompleted);
            }
            this.InvokeAsync("RemoveTelefon", new object[] {
                        lstItems}, this.RemoveTelefonOperationCompleted, userState);
        }
        
        private void OnRemoveTelefonOperationCompleted(object arg) {
            if ((this.RemoveTelefonCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RemoveTelefonCompleted(this, new RemoveTelefonCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("PTJSoapHeaderValue", Direction=System.Web.Services.Protocols.SoapHeaderDirection.InOut)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetCurrentTimeView", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.DateTime GetCurrentTimeView() {
            object[] results = this.Invoke("GetCurrentTimeView", new object[0]);
            return ((System.DateTime)(results[0]));
        }
        
        /// <remarks/>
        public void GetCurrentTimeViewAsync() {
            this.GetCurrentTimeViewAsync(null);
        }
        
        /// <remarks/>
        public void GetCurrentTimeViewAsync(object userState) {
            if ((this.GetCurrentTimeViewOperationCompleted == null)) {
                this.GetCurrentTimeViewOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCurrentTimeViewOperationCompleted);
            }
            this.InvokeAsync("GetCurrentTimeView", new object[0], this.GetCurrentTimeViewOperationCompleted, userState);
        }
        
        private void OnGetCurrentTimeViewOperationCompleted(object arg) {
            if ((this.GetCurrentTimeViewCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCurrentTimeViewCompleted(this, new GetCurrentTimeViewCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("PTJSoapHeaderValue", Direction=System.Web.Services.Protocols.SoapHeaderDirection.InOut)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SetCurrentTimeView", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SetCurrentTimeView(System.DateTime dt) {
            this.Invoke("SetCurrentTimeView", new object[] {
                        dt});
        }
        
        /// <remarks/>
        public void SetCurrentTimeViewAsync(System.DateTime dt) {
            this.SetCurrentTimeViewAsync(dt, null);
        }
        
        /// <remarks/>
        public void SetCurrentTimeViewAsync(System.DateTime dt, object userState) {
            if ((this.SetCurrentTimeViewOperationCompleted == null)) {
                this.SetCurrentTimeViewOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetCurrentTimeViewOperationCompleted);
            }
            this.InvokeAsync("SetCurrentTimeView", new object[] {
                        dt}, this.SetCurrentTimeViewOperationCompleted, userState);
        }
        
        private void OnSetCurrentTimeViewOperationCompleted(object arg) {
            if ((this.SetCurrentTimeViewCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetCurrentTimeViewCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/", IsNullable=false)]
    public partial class PTJSoapHeader : System.Web.Services.Protocols.SoapHeader {
        
        private System.DateTime timeViewField;
        
        private string currentUserField;
        
        private string currentDataRoleField;
        
        private string currentRowLevelSecurityField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public System.DateTime TimeView {
            get {
                return this.timeViewField;
            }
            set {
                this.timeViewField = value;
            }
        }
        
        /// <remarks/>
        public string CurrentUser {
            get {
                return this.currentUserField;
            }
            set {
                this.currentUserField = value;
            }
        }
        
        /// <remarks/>
        public string CurrentDataRole {
            get {
                return this.currentDataRoleField;
            }
            set {
                this.currentDataRoleField = value;
            }
        }
        
        /// <remarks/>
        public string CurrentRowLevelSecurity {
            get {
                return this.currentRowLevelSecurityField;
            }
            set {
                this.currentRowLevelSecurityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class AdressSchema {
        
        private int idField;
        
        private int adressTyp_FKIDField;
        
        private int person_FKIDField;
        
        private int organisation_FKIDField;
        
        private int adressVariant_FKIDField;
        
        private System.DateTime skapadDatumField;
        
        private System.DateTime updateradDatumField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public int AdressTyp_FKID {
            get {
                return this.adressTyp_FKIDField;
            }
            set {
                this.adressTyp_FKIDField = value;
            }
        }
        
        /// <remarks/>
        public int Person_FKID {
            get {
                return this.person_FKIDField;
            }
            set {
                this.person_FKIDField = value;
            }
        }
        
        /// <remarks/>
        public int Organisation_FKID {
            get {
                return this.organisation_FKIDField;
            }
            set {
                this.organisation_FKIDField = value;
            }
        }
        
        /// <remarks/>
        public int AdressVariant_FKID {
            get {
                return this.adressVariant_FKIDField;
            }
            set {
                this.adressVariant_FKIDField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime SkapadDatum {
            get {
                return this.skapadDatumField;
            }
            set {
                this.skapadDatumField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime UpdateradDatum {
            get {
                return this.updateradDatumField;
            }
            set {
                this.updateradDatumField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class KeyValueOfTelefonSchemaAdressSchema {
        
        private TelefonSchema keyField;
        
        private AdressSchema valueField;
        
        /// <remarks/>
        public TelefonSchema Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        public AdressSchema Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class TelefonSchema {
        
        private int idField;
        
        private int adress_FKIDField;
        
        private int adressTyp_FKIDField;
        
        private int adressVariant_FKIDField;
        
        private int telefonNummerField;
        
        private System.DateTime skapadDatumField;
        
        private System.DateTime updateradDatumField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public int Adress_FKID {
            get {
                return this.adress_FKIDField;
            }
            set {
                this.adress_FKIDField = value;
            }
        }
        
        /// <remarks/>
        public int AdressTyp_FKID {
            get {
                return this.adressTyp_FKIDField;
            }
            set {
                this.adressTyp_FKIDField = value;
            }
        }
        
        /// <remarks/>
        public int AdressVariant_FKID {
            get {
                return this.adressVariant_FKIDField;
            }
            set {
                this.adressVariant_FKIDField = value;
            }
        }
        
        /// <remarks/>
        public int TelefonNummer {
            get {
                return this.telefonNummerField;
            }
            set {
                this.telefonNummerField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime SkapadDatum {
            get {
                return this.skapadDatumField;
            }
            set {
                this.skapadDatumField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime UpdateradDatum {
            get {
                return this.updateradDatumField;
            }
            set {
                this.updateradDatumField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class TransportMessageOfArrayOfKeyValueOfTelefonSchemaAdressSchema {
        
        private KeyValueOfTelefonSchemaAdressSchema[] resultsField;
        
        private Message[] lstMessagesField;
        
        private KeyValueOfTelefonSchemaAdressSchema[] dataField;
        
        private Message[] messagesField;
        
        /// <remarks/>
        public KeyValueOfTelefonSchemaAdressSchema[] Results {
            get {
                return this.resultsField;
            }
            set {
                this.resultsField = value;
            }
        }
        
        /// <remarks/>
        public Message[] lstMessages {
            get {
                return this.lstMessagesField;
            }
            set {
                this.lstMessagesField = value;
            }
        }
        
        /// <remarks/>
        public KeyValueOfTelefonSchemaAdressSchema[] Data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
            }
        }
        
        /// <remarks/>
        public Message[] Messages {
            get {
                return this.messagesField;
            }
            set {
                this.messagesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Message {
        
        private int ordinalField;
        
        private MessageType msgTypeField;
        
        private System.DateTime eventTimeField;
        
        private string exceptionMessageField;
        
        private int ordinalField1;
        
        private MessageType msgTypeField1;
        
        private System.DateTime eventTimeField1;
        
        private string exceptionMessageField1;
        
        /// <remarks/>
        public int Ordinal {
            get {
                return this.ordinalField;
            }
            set {
                this.ordinalField = value;
            }
        }
        
        /// <remarks/>
        public MessageType msgType {
            get {
                return this.msgTypeField;
            }
            set {
                this.msgTypeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime EventTime {
            get {
                return this.eventTimeField;
            }
            set {
                this.eventTimeField = value;
            }
        }
        
        /// <remarks/>
        public string ExceptionMessage {
            get {
                return this.exceptionMessageField;
            }
            set {
                this.exceptionMessageField = value;
            }
        }
        
        /// <remarks/>
        public int ordinal {
            get {
                return this.ordinalField1;
            }
            set {
                this.ordinalField1 = value;
            }
        }
        
        /// <remarks/>
        public MessageType MsgType {
            get {
                return this.msgTypeField1;
            }
            set {
                this.msgTypeField1 = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime eventTime {
            get {
                return this.eventTimeField1;
            }
            set {
                this.eventTimeField1 = value;
            }
        }
        
        /// <remarks/>
        public string exceptionMessage {
            get {
                return this.exceptionMessageField1;
            }
            set {
                this.exceptionMessageField1 = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum MessageType {
        
        /// <remarks/>
        Nothing,
        
        /// <remarks/>
        Information,
        
        /// <remarks/>
        Validation,
        
        /// <remarks/>
        Security,
        
        /// <remarks/>
        Warning,
        
        /// <remarks/>
        Abbend,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class TransportMessageOfTelefonSchema {
        
        private TelefonSchema resultsField;
        
        private Message[] lstMessagesField;
        
        private TelefonSchema dataField;
        
        private Message[] messagesField;
        
        /// <remarks/>
        public TelefonSchema Results {
            get {
                return this.resultsField;
            }
            set {
                this.resultsField = value;
            }
        }
        
        /// <remarks/>
        public Message[] lstMessages {
            get {
                return this.lstMessagesField;
            }
            set {
                this.lstMessagesField = value;
            }
        }
        
        /// <remarks/>
        public TelefonSchema Data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
            }
        }
        
        /// <remarks/>
        public Message[] Messages {
            get {
                return this.messagesField;
            }
            set {
                this.messagesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class TransportMessageOfArrayOfTelefonSchema {
        
        private TelefonSchema[] resultsField;
        
        private Message[] lstMessagesField;
        
        private TelefonSchema[] dataField;
        
        private Message[] messagesField;
        
        /// <remarks/>
        public TelefonSchema[] Results {
            get {
                return this.resultsField;
            }
            set {
                this.resultsField = value;
            }
        }
        
        /// <remarks/>
        public Message[] lstMessages {
            get {
                return this.lstMessagesField;
            }
            set {
                this.lstMessagesField = value;
            }
        }
        
        /// <remarks/>
        public TelefonSchema[] Data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
            }
        }
        
        /// <remarks/>
        public Message[] Messages {
            get {
                return this.messagesField;
            }
            set {
                this.messagesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetAllCompletedEventHandler(object sender, GetAllCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TransportMessageOfArrayOfTelefonSchema Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TransportMessageOfArrayOfTelefonSchema)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetByIdCompletedEventHandler(object sender, GetByIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetByIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetByIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TransportMessageOfTelefonSchema Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TransportMessageOfTelefonSchema)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetByAdressCompletedEventHandler(object sender, GetByAdressCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetByAdressCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetByAdressCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TransportMessageOfArrayOfKeyValueOfTelefonSchemaAdressSchema Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TransportMessageOfArrayOfKeyValueOfTelefonSchemaAdressSchema)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetByTelefonNumberCompletedEventHandler(object sender, GetByTelefonNumberCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetByTelefonNumberCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetByTelefonNumberCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TransportMessageOfArrayOfTelefonSchema Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TransportMessageOfArrayOfTelefonSchema)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void AddTelefonCompletedEventHandler(object sender, AddTelefonCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddTelefonCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddTelefonCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TransportMessageOfArrayOfTelefonSchema Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TransportMessageOfArrayOfTelefonSchema)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void ChangeTelefonCompletedEventHandler(object sender, ChangeTelefonCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ChangeTelefonCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ChangeTelefonCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TransportMessageOfArrayOfTelefonSchema Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TransportMessageOfArrayOfTelefonSchema)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void RemoveTelefonCompletedEventHandler(object sender, RemoveTelefonCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RemoveTelefonCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RemoveTelefonCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TransportMessageOfArrayOfTelefonSchema Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TransportMessageOfArrayOfTelefonSchema)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetCurrentTimeViewCompletedEventHandler(object sender, GetCurrentTimeViewCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCurrentTimeViewCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCurrentTimeViewCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.DateTime Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.DateTime)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void SetCurrentTimeViewCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591