//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace PTJ.Person.Presentation.GatuAdressService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="GatuAdressServiceSoap", Namespace="http://tempuri.org/")]
    public partial class GatuAdressService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private PTJSoapHeader pTJSoapHeaderValueField;
        
        private System.Threading.SendOrPostCallback GetAllOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetByIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetByAdressOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetByGatuAdressOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddGatuAdressOperationCompleted;
        
        private System.Threading.SendOrPostCallback ChangeGatuAdressOperationCompleted;
        
        private System.Threading.SendOrPostCallback RemoveGatuAdressOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCurrentTimeViewOperationCompleted;
        
        private System.Threading.SendOrPostCallback SetCurrentTimeViewOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public GatuAdressService() {
            this.Url = global::PTJ.Person.Presentation.Properties.Settings.Default.PTJ_Person_Presentation_GatuAdressService_GatuAdressService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public PTJSoapHeader PTJSoapHeaderValue {
            get {
                return this.pTJSoapHeaderValueField;
            }
            set {
                this.pTJSoapHeaderValueField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetAllCompletedEventHandler GetAllCompleted;
        
        /// <remarks/>
        public event GetByIdCompletedEventHandler GetByIdCompleted;
        
        /// <remarks/>
        public event GetByAdressCompletedEventHandler GetByAdressCompleted;
        
        /// <remarks/>
        public event GetByGatuAdressCompletedEventHandler GetByGatuAdressCompleted;
        
        /// <remarks/>
        public event AddGatuAdressCompletedEventHandler AddGatuAdressCompleted;
        
        /// <remarks/>
        public event ChangeGatuAdressCompletedEventHandler ChangeGatuAdressCompleted;
        
        /// <remarks/>
        public event RemoveGatuAdressCompletedEventHandler RemoveGatuAdressCompleted;
        
        /// <remarks/>
        public event GetCurrentTimeViewCompletedEventHandler GetCurrentTimeViewCompleted;
        
        /// <remarks/>
        public event SetCurrentTimeViewCompletedEventHandler SetCurrentTimeViewCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("PTJSoapHeaderValue", Direction=System.Web.Services.Protocols.SoapHeaderDirection.InOut)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAll", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TransportMessageOfArrayOfGatuAdressSchema GetAll() {
            object[] results = this.Invoke("GetAll", new object[0]);
            return ((TransportMessageOfArrayOfGatuAdressSchema)(results[0]));
        }
        
        /// <remarks/>
        public void GetAllAsync() {
            this.GetAllAsync(null);
        }
        
        /// <remarks/>
        public void GetAllAsync(object userState) {
            if ((this.GetAllOperationCompleted == null)) {
                this.GetAllOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllOperationCompleted);
            }
            this.InvokeAsync("GetAll", new object[0], this.GetAllOperationCompleted, userState);
        }
        
        private void OnGetAllOperationCompleted(object arg) {
            if ((this.GetAllCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllCompleted(this, new GetAllCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("PTJSoapHeaderValue", Direction=System.Web.Services.Protocols.SoapHeaderDirection.InOut)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ById", RequestElementName="ById", RequestNamespace="http://tempuri.org/", ResponseElementName="ByIdResponse", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("ByIdResult")]
        public TransportMessageOfGatuAdressSchema GetById(int id) {
            object[] results = this.Invoke("GetById", new object[] {
                        id});
            return ((TransportMessageOfGatuAdressSchema)(results[0]));
        }
        
        /// <remarks/>
        public void GetByIdAsync(int id) {
            this.GetByIdAsync(id, null);
        }
        
        /// <remarks/>
        public void GetByIdAsync(int id, object userState) {
            if ((this.GetByIdOperationCompleted == null)) {
                this.GetByIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetByIdOperationCompleted);
            }
            this.InvokeAsync("GetById", new object[] {
                        id}, this.GetByIdOperationCompleted, userState);
        }
        
        private void OnGetByIdOperationCompleted(object arg) {
            if ((this.GetByIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetByIdCompleted(this, new GetByIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("PTJSoapHeaderValue", Direction=System.Web.Services.Protocols.SoapHeaderDirection.InOut)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetByAdress", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TransportMessageOfArrayOfKeyValueOfGatuAdressSchemaAdressSchema GetByAdress(int id) {
            object[] results = this.Invoke("GetByAdress", new object[] {
                        id});
            return ((TransportMessageOfArrayOfKeyValueOfGatuAdressSchemaAdressSchema)(results[0]));
        }
        
        /// <remarks/>
        public void GetByAdressAsync(int id) {
            this.GetByAdressAsync(id, null);
        }
        
        /// <remarks/>
        public void GetByAdressAsync(int id, object userState) {
            if ((this.GetByAdressOperationCompleted == null)) {
                this.GetByAdressOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetByAdressOperationCompleted);
            }
            this.InvokeAsync("GetByAdress", new object[] {
                        id}, this.GetByAdressOperationCompleted, userState);
        }
        
        private void OnGetByAdressOperationCompleted(object arg) {
            if ((this.GetByAdressCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetByAdressCompleted(this, new GetByAdressCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("PTJSoapHeaderValue", Direction=System.Web.Services.Protocols.SoapHeaderDirection.InOut)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetByGatuAdress", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TransportMessageOfArrayOfGatuAdressSchema GetByGatuAdress(string name) {
            object[] results = this.Invoke("GetByGatuAdress", new object[] {
                        name});
            return ((TransportMessageOfArrayOfGatuAdressSchema)(results[0]));
        }
        
        /// <remarks/>
        public void GetByGatuAdressAsync(string name) {
            this.GetByGatuAdressAsync(name, null);
        }
        
        /// <remarks/>
        public void GetByGatuAdressAsync(string name, object userState) {
            if ((this.GetByGatuAdressOperationCompleted == null)) {
                this.GetByGatuAdressOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetByGatuAdressOperationCompleted);
            }
            this.InvokeAsync("GetByGatuAdress", new object[] {
                        name}, this.GetByGatuAdressOperationCompleted, userState);
        }
        
        private void OnGetByGatuAdressOperationCompleted(object arg) {
            if ((this.GetByGatuAdressCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetByGatuAdressCompleted(this, new GetByGatuAdressCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("PTJSoapHeaderValue", Direction=System.Web.Services.Protocols.SoapHeaderDirection.InOut)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AddGatuAdress", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TransportMessageOfArrayOfGatuAdressSchema AddGatuAdress(GatuAdressSchema[] lstItems) {
            object[] results = this.Invoke("AddGatuAdress", new object[] {
                        lstItems});
            return ((TransportMessageOfArrayOfGatuAdressSchema)(results[0]));
        }
        
        /// <remarks/>
        public void AddGatuAdressAsync(GatuAdressSchema[] lstItems) {
            this.AddGatuAdressAsync(lstItems, null);
        }
        
        /// <remarks/>
        public void AddGatuAdressAsync(GatuAdressSchema[] lstItems, object userState) {
            if ((this.AddGatuAdressOperationCompleted == null)) {
                this.AddGatuAdressOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddGatuAdressOperationCompleted);
            }
            this.InvokeAsync("AddGatuAdress", new object[] {
                        lstItems}, this.AddGatuAdressOperationCompleted, userState);
        }
        
        private void OnAddGatuAdressOperationCompleted(object arg) {
            if ((this.AddGatuAdressCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddGatuAdressCompleted(this, new AddGatuAdressCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("PTJSoapHeaderValue", Direction=System.Web.Services.Protocols.SoapHeaderDirection.InOut)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ChangeGatuAdress", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TransportMessageOfArrayOfGatuAdressSchema ChangeGatuAdress(GatuAdressSchema[] lstItems) {
            object[] results = this.Invoke("ChangeGatuAdress", new object[] {
                        lstItems});
            return ((TransportMessageOfArrayOfGatuAdressSchema)(results[0]));
        }
        
        /// <remarks/>
        public void ChangeGatuAdressAsync(GatuAdressSchema[] lstItems) {
            this.ChangeGatuAdressAsync(lstItems, null);
        }
        
        /// <remarks/>
        public void ChangeGatuAdressAsync(GatuAdressSchema[] lstItems, object userState) {
            if ((this.ChangeGatuAdressOperationCompleted == null)) {
                this.ChangeGatuAdressOperationCompleted = new System.Threading.SendOrPostCallback(this.OnChangeGatuAdressOperationCompleted);
            }
            this.InvokeAsync("ChangeGatuAdress", new object[] {
                        lstItems}, this.ChangeGatuAdressOperationCompleted, userState);
        }
        
        private void OnChangeGatuAdressOperationCompleted(object arg) {
            if ((this.ChangeGatuAdressCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ChangeGatuAdressCompleted(this, new ChangeGatuAdressCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("PTJSoapHeaderValue", Direction=System.Web.Services.Protocols.SoapHeaderDirection.InOut)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RemoveGatuAdress", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TransportMessageOfArrayOfGatuAdressSchema RemoveGatuAdress(GatuAdressSchema[] lstItems) {
            object[] results = this.Invoke("RemoveGatuAdress", new object[] {
                        lstItems});
            return ((TransportMessageOfArrayOfGatuAdressSchema)(results[0]));
        }
        
        /// <remarks/>
        public void RemoveGatuAdressAsync(GatuAdressSchema[] lstItems) {
            this.RemoveGatuAdressAsync(lstItems, null);
        }
        
        /// <remarks/>
        public void RemoveGatuAdressAsync(GatuAdressSchema[] lstItems, object userState) {
            if ((this.RemoveGatuAdressOperationCompleted == null)) {
                this.RemoveGatuAdressOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRemoveGatuAdressOperationCompleted);
            }
            this.InvokeAsync("RemoveGatuAdress", new object[] {
                        lstItems}, this.RemoveGatuAdressOperationCompleted, userState);
        }
        
        private void OnRemoveGatuAdressOperationCompleted(object arg) {
            if ((this.RemoveGatuAdressCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RemoveGatuAdressCompleted(this, new RemoveGatuAdressCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("PTJSoapHeaderValue", Direction=System.Web.Services.Protocols.SoapHeaderDirection.InOut)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetCurrentTimeView", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.DateTime GetCurrentTimeView() {
            object[] results = this.Invoke("GetCurrentTimeView", new object[0]);
            return ((System.DateTime)(results[0]));
        }
        
        /// <remarks/>
        public void GetCurrentTimeViewAsync() {
            this.GetCurrentTimeViewAsync(null);
        }
        
        /// <remarks/>
        public void GetCurrentTimeViewAsync(object userState) {
            if ((this.GetCurrentTimeViewOperationCompleted == null)) {
                this.GetCurrentTimeViewOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCurrentTimeViewOperationCompleted);
            }
            this.InvokeAsync("GetCurrentTimeView", new object[0], this.GetCurrentTimeViewOperationCompleted, userState);
        }
        
        private void OnGetCurrentTimeViewOperationCompleted(object arg) {
            if ((this.GetCurrentTimeViewCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCurrentTimeViewCompleted(this, new GetCurrentTimeViewCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("PTJSoapHeaderValue", Direction=System.Web.Services.Protocols.SoapHeaderDirection.InOut)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SetCurrentTimeView", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SetCurrentTimeView(System.DateTime dt) {
            this.Invoke("SetCurrentTimeView", new object[] {
                        dt});
        }
        
        /// <remarks/>
        public void SetCurrentTimeViewAsync(System.DateTime dt) {
            this.SetCurrentTimeViewAsync(dt, null);
        }
        
        /// <remarks/>
        public void SetCurrentTimeViewAsync(System.DateTime dt, object userState) {
            if ((this.SetCurrentTimeViewOperationCompleted == null)) {
                this.SetCurrentTimeViewOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetCurrentTimeViewOperationCompleted);
            }
            this.InvokeAsync("SetCurrentTimeView", new object[] {
                        dt}, this.SetCurrentTimeViewOperationCompleted, userState);
        }
        
        private void OnSetCurrentTimeViewOperationCompleted(object arg) {
            if ((this.SetCurrentTimeViewCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetCurrentTimeViewCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/", IsNullable=false)]
    public partial class PTJSoapHeader : System.Web.Services.Protocols.SoapHeader {
        
        private System.DateTime timeViewField;
        
        private string currentUserField;
        
        private string currentDataRoleField;
        
        private string currentRowLevelSecurityField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public System.DateTime TimeView {
            get {
                return this.timeViewField;
            }
            set {
                this.timeViewField = value;
            }
        }
        
        /// <remarks/>
        public string CurrentUser {
            get {
                return this.currentUserField;
            }
            set {
                this.currentUserField = value;
            }
        }
        
        /// <remarks/>
        public string CurrentDataRole {
            get {
                return this.currentDataRoleField;
            }
            set {
                this.currentDataRoleField = value;
            }
        }
        
        /// <remarks/>
        public string CurrentRowLevelSecurity {
            get {
                return this.currentRowLevelSecurityField;
            }
            set {
                this.currentRowLevelSecurityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class AdressSchema {
        
        private int idField;
        
        private int adressTyp_FKIDField;
        
        private int person_FKIDField;
        
        private int organisation_FKIDField;
        
        private int adressVariant_FKIDField;
        
        private System.DateTime skapadDatumField;
        
        private System.DateTime updateradDatumField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public int AdressTyp_FKID {
            get {
                return this.adressTyp_FKIDField;
            }
            set {
                this.adressTyp_FKIDField = value;
            }
        }
        
        /// <remarks/>
        public int Person_FKID {
            get {
                return this.person_FKIDField;
            }
            set {
                this.person_FKIDField = value;
            }
        }
        
        /// <remarks/>
        public int Organisation_FKID {
            get {
                return this.organisation_FKIDField;
            }
            set {
                this.organisation_FKIDField = value;
            }
        }
        
        /// <remarks/>
        public int AdressVariant_FKID {
            get {
                return this.adressVariant_FKIDField;
            }
            set {
                this.adressVariant_FKIDField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime SkapadDatum {
            get {
                return this.skapadDatumField;
            }
            set {
                this.skapadDatumField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime UpdateradDatum {
            get {
                return this.updateradDatumField;
            }
            set {
                this.updateradDatumField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class KeyValueOfGatuAdressSchemaAdressSchema {
        
        private GatuAdressSchema keyField;
        
        private AdressSchema valueField;
        
        /// <remarks/>
        public GatuAdressSchema Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        public AdressSchema Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class GatuAdressSchema {
        
        private int idField;
        
        private int adress_FKIDField;
        
        private int adressTyp_FKIDField;
        
        private int adressVariant_FKIDField;
        
        private string adressRad1Field;
        
        private string adressRad2Field;
        
        private string adressRad3Field;
        
        private string adressRad4Field;
        
        private string adressRad5Field;
        
        private int postnummerField;
        
        private string stadField;
        
        private string landField;
        
        private System.DateTime skapadDatumField;
        
        private System.DateTime updateradDatumField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public int Adress_FKID {
            get {
                return this.adress_FKIDField;
            }
            set {
                this.adress_FKIDField = value;
            }
        }
        
        /// <remarks/>
        public int AdressTyp_FKID {
            get {
                return this.adressTyp_FKIDField;
            }
            set {
                this.adressTyp_FKIDField = value;
            }
        }
        
        /// <remarks/>
        public int AdressVariant_FKID {
            get {
                return this.adressVariant_FKIDField;
            }
            set {
                this.adressVariant_FKIDField = value;
            }
        }
        
        /// <remarks/>
        public string AdressRad1 {
            get {
                return this.adressRad1Field;
            }
            set {
                this.adressRad1Field = value;
            }
        }
        
        /// <remarks/>
        public string AdressRad2 {
            get {
                return this.adressRad2Field;
            }
            set {
                this.adressRad2Field = value;
            }
        }
        
        /// <remarks/>
        public string AdressRad3 {
            get {
                return this.adressRad3Field;
            }
            set {
                this.adressRad3Field = value;
            }
        }
        
        /// <remarks/>
        public string AdressRad4 {
            get {
                return this.adressRad4Field;
            }
            set {
                this.adressRad4Field = value;
            }
        }
        
        /// <remarks/>
        public string AdressRad5 {
            get {
                return this.adressRad5Field;
            }
            set {
                this.adressRad5Field = value;
            }
        }
        
        /// <remarks/>
        public int Postnummer {
            get {
                return this.postnummerField;
            }
            set {
                this.postnummerField = value;
            }
        }
        
        /// <remarks/>
        public string Stad {
            get {
                return this.stadField;
            }
            set {
                this.stadField = value;
            }
        }
        
        /// <remarks/>
        public string Land {
            get {
                return this.landField;
            }
            set {
                this.landField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime SkapadDatum {
            get {
                return this.skapadDatumField;
            }
            set {
                this.skapadDatumField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime UpdateradDatum {
            get {
                return this.updateradDatumField;
            }
            set {
                this.updateradDatumField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class TransportMessageOfArrayOfKeyValueOfGatuAdressSchemaAdressSchema {
        
        private KeyValueOfGatuAdressSchemaAdressSchema[] resultsField;
        
        private Message[] lstMessagesField;
        
        private KeyValueOfGatuAdressSchemaAdressSchema[] dataField;
        
        private Message[] messagesField;
        
        /// <remarks/>
        public KeyValueOfGatuAdressSchemaAdressSchema[] Results {
            get {
                return this.resultsField;
            }
            set {
                this.resultsField = value;
            }
        }
        
        /// <remarks/>
        public Message[] lstMessages {
            get {
                return this.lstMessagesField;
            }
            set {
                this.lstMessagesField = value;
            }
        }
        
        /// <remarks/>
        public KeyValueOfGatuAdressSchemaAdressSchema[] Data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
            }
        }
        
        /// <remarks/>
        public Message[] Messages {
            get {
                return this.messagesField;
            }
            set {
                this.messagesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Message {
        
        private int ordinalField;
        
        private MessageType msgTypeField;
        
        private System.DateTime eventTimeField;
        
        private string exceptionMessageField;
        
        private int ordinalField1;
        
        private MessageType msgTypeField1;
        
        private System.DateTime eventTimeField1;
        
        private string exceptionMessageField1;
        
        /// <remarks/>
        public int Ordinal {
            get {
                return this.ordinalField;
            }
            set {
                this.ordinalField = value;
            }
        }
        
        /// <remarks/>
        public MessageType msgType {
            get {
                return this.msgTypeField;
            }
            set {
                this.msgTypeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime EventTime {
            get {
                return this.eventTimeField;
            }
            set {
                this.eventTimeField = value;
            }
        }
        
        /// <remarks/>
        public string ExceptionMessage {
            get {
                return this.exceptionMessageField;
            }
            set {
                this.exceptionMessageField = value;
            }
        }
        
        /// <remarks/>
        public int ordinal {
            get {
                return this.ordinalField1;
            }
            set {
                this.ordinalField1 = value;
            }
        }
        
        /// <remarks/>
        public MessageType MsgType {
            get {
                return this.msgTypeField1;
            }
            set {
                this.msgTypeField1 = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime eventTime {
            get {
                return this.eventTimeField1;
            }
            set {
                this.eventTimeField1 = value;
            }
        }
        
        /// <remarks/>
        public string exceptionMessage {
            get {
                return this.exceptionMessageField1;
            }
            set {
                this.exceptionMessageField1 = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum MessageType {
        
        /// <remarks/>
        Nothing,
        
        /// <remarks/>
        Information,
        
        /// <remarks/>
        Validation,
        
        /// <remarks/>
        Security,
        
        /// <remarks/>
        Warning,
        
        /// <remarks/>
        Abbend,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class TransportMessageOfGatuAdressSchema {
        
        private GatuAdressSchema resultsField;
        
        private Message[] lstMessagesField;
        
        private GatuAdressSchema dataField;
        
        private Message[] messagesField;
        
        /// <remarks/>
        public GatuAdressSchema Results {
            get {
                return this.resultsField;
            }
            set {
                this.resultsField = value;
            }
        }
        
        /// <remarks/>
        public Message[] lstMessages {
            get {
                return this.lstMessagesField;
            }
            set {
                this.lstMessagesField = value;
            }
        }
        
        /// <remarks/>
        public GatuAdressSchema Data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
            }
        }
        
        /// <remarks/>
        public Message[] Messages {
            get {
                return this.messagesField;
            }
            set {
                this.messagesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class TransportMessageOfArrayOfGatuAdressSchema {
        
        private GatuAdressSchema[] resultsField;
        
        private Message[] lstMessagesField;
        
        private GatuAdressSchema[] dataField;
        
        private Message[] messagesField;
        
        /// <remarks/>
        public GatuAdressSchema[] Results {
            get {
                return this.resultsField;
            }
            set {
                this.resultsField = value;
            }
        }
        
        /// <remarks/>
        public Message[] lstMessages {
            get {
                return this.lstMessagesField;
            }
            set {
                this.lstMessagesField = value;
            }
        }
        
        /// <remarks/>
        public GatuAdressSchema[] Data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
            }
        }
        
        /// <remarks/>
        public Message[] Messages {
            get {
                return this.messagesField;
            }
            set {
                this.messagesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetAllCompletedEventHandler(object sender, GetAllCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TransportMessageOfArrayOfGatuAdressSchema Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TransportMessageOfArrayOfGatuAdressSchema)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetByIdCompletedEventHandler(object sender, GetByIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetByIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetByIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TransportMessageOfGatuAdressSchema Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TransportMessageOfGatuAdressSchema)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetByAdressCompletedEventHandler(object sender, GetByAdressCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetByAdressCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetByAdressCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TransportMessageOfArrayOfKeyValueOfGatuAdressSchemaAdressSchema Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TransportMessageOfArrayOfKeyValueOfGatuAdressSchemaAdressSchema)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetByGatuAdressCompletedEventHandler(object sender, GetByGatuAdressCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetByGatuAdressCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetByGatuAdressCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TransportMessageOfArrayOfGatuAdressSchema Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TransportMessageOfArrayOfGatuAdressSchema)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void AddGatuAdressCompletedEventHandler(object sender, AddGatuAdressCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddGatuAdressCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddGatuAdressCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TransportMessageOfArrayOfGatuAdressSchema Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TransportMessageOfArrayOfGatuAdressSchema)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void ChangeGatuAdressCompletedEventHandler(object sender, ChangeGatuAdressCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ChangeGatuAdressCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ChangeGatuAdressCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TransportMessageOfArrayOfGatuAdressSchema Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TransportMessageOfArrayOfGatuAdressSchema)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void RemoveGatuAdressCompletedEventHandler(object sender, RemoveGatuAdressCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RemoveGatuAdressCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RemoveGatuAdressCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TransportMessageOfArrayOfGatuAdressSchema Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TransportMessageOfArrayOfGatuAdressSchema)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetCurrentTimeViewCompletedEventHandler(object sender, GetCurrentTimeViewCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCurrentTimeViewCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCurrentTimeViewCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.DateTime Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.DateTime)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void SetCurrentTimeViewCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591